import { getTableName } from "drizzle-orm";

import {
  authAccounts,
  authSessions,
  auditLogs,
  documentBlocks,
  documentChunks,
  documentCrdtSnapshots,
  documentDiscussionReadStates,
  documentReviewStates,
  documents,
  documentVersions,
  mediaObjects,
  mediaDeletionJobs,
  mediaUploads,
  mediaUsages,
  moduleRecords,
  moduleTemplateFields,
  moduleTemplates,
  projectModuleFields,
  projectModules,
  projectRecents,
  projects,
  searchItems,
  systemModuleTemplateFields,
  systemModuleTemplates,
  tenantMemberships,
  tenants,
  users,
} from "./schema";

const sharebrainTables = [
  authAccounts,
  authSessions,
  auditLogs,
  documentBlocks,
  documentChunks,
  documentCrdtSnapshots,
  documentDiscussionReadStates,
  documentReviewStates,
  documents,
  documentVersions,
  mediaObjects,
  mediaDeletionJobs,
  mediaUploads,
  mediaUsages,
  moduleRecords,
  moduleTemplateFields,
  moduleTemplates,
  projectModuleFields,
  projectModules,
  projectRecents,
  projects,
  searchItems,
  systemModuleTemplateFields,
  systemModuleTemplates,
  tenantMemberships,
  tenants,
  users,
] as const;

export const sharebrainTableNames = sharebrainTables.map((table) => getTableName(table)).sort();
