import { loadClientEnv } from "@sharebrain/config";

export const runtimeEnv = loadClientEnv({
  WEB_PUBLIC_API_BASE_URL:
    import.meta.env.WEB_PUBLIC_API_BASE_URL ?? "",
  WEB_PUBLIC_COLLAB_WS_URL:
    import.meta.env.WEB_PUBLIC_COLLAB_WS_URL ?? "ws://localhost:3002",
  WEB_PUBLIC_EDITOR_WINDOWING_ENABLED:
    import.meta.env.WEB_PUBLIC_EDITOR_WINDOWING_ENABLED ?? "true",
  WEB_PUBLIC_EDITOR_WINDOWING_MIN_BLOCKS:
    import.meta.env.WEB_PUBLIC_EDITOR_WINDOWING_MIN_BLOCKS ?? "800",
  WEB_PUBLIC_EDITOR_WINDOWING_LONG_TASK_MS:
    import.meta.env.WEB_PUBLIC_EDITOR_WINDOWING_LONG_TASK_MS ?? "200",
  WEB_PUBLIC_EDITOR_WINDOWING_MAX_FALLBACK_RATIO:
    import.meta.env.WEB_PUBLIC_EDITOR_WINDOWING_MAX_FALLBACK_RATIO ?? "0.25",
  WEB_PUBLIC_EDITOR_WINDOWING_MAX_REVEAL_FAILURES:
    import.meta.env.WEB_PUBLIC_EDITOR_WINDOWING_MAX_REVEAL_FAILURES ?? "3",
});
